# five main fields
ID = 'ID'
NAME = 'NAME'
ADDRESS = 'ADDRESS'
CITY = 'CITY'
TYPE = 'TYPE'

sourceData = 'sourceData'
sgidName = 'sgidName'
name = 'name'
description = 'description'
metaDataUrl = 'metaDataUrl'
heading = 'heading'
geometryType = 'geometryType'
url = 'url'
index = 'index'
fields = 'fields'
docLink = 'docLink'
gramaLink = 'gramaLink'
additionalLink = 'additionalLink'

queryLayers = 'queryLayers'
otherLinks = 'otherLinks'
