# five main fields
ID = 'ID'
NAME = 'NAME'
ADDRESS = 'ADDRESS'
CITY = 'CITY'
TYPE = 'TYPE'
ENVIROAPPLABEL = 'ENVIROAPPLABEL'
ENVIROAPPSYMBOL = 'ENVIROAPPSYMBOL'

sourceData = 'sourceData'
sgidName = 'sgidName'
name = 'name'
description = 'description'
metaDataUrl = 'metaDataUrl'
heading = 'heading'
geometryType = 'geometryType'
etlType = 'etlType'
url = 'url'
index = 'index'
fields = 'fields'
docLink = 'docLink'
gramaLink = 'gramaLink'
permitLink = 'permitLink'
additionalLink = 'additionalLink'
additionalLinkFields = 'additionalLinkFields'
secure = 'secure'
specialFilters = 'specialFilters'
specialFiltersDefaultOn = 'specialFiltersDefaultOn'
additionalSearches = 'additionalSearches'
sortField = 'sortField'
legendTitle = 'legendTitle'
codedValues = 'codedValues'
oidField = 'oidField'

queryLayers = 'queryLayers'
relatedTables = 'relatedTables'
otherLinks = 'otherLinks'

relationshipName = 'Relationship Name'
relatedTableName = 'Related Table Name'
parentDatasetName = 'Parent Dataset Name'
primaryKey = 'Primary Key'
foreignKey = 'Foreign Key'

# NHD Data
GNIS_Name = 'GNIS_Name'
COUNTY = 'COUNTY'
