packages:
  - functions

onlyBuiltDependencies:
  - '@firebase/util'
  - '@parcel/watcher'
  - '@vaadin/vaadin-usage-statistics'
  - core-js
  - esbuild
  - protobufjs
  - re2

overrides:
  happy-dom@<20.0.0: '>=20.0.0'
  happy-dom@<20.0.2: '>=20.0.2'
  tmp@<=0.2.3: '>=0.2.4'
  vite@>=6.0.0 <=6.4.0: '>=6.4.1'
