packages:
  - functions

minimumReleaseAge: 10080
minimumReleaseAgeStrict: true

minimumReleaseAgeExclude:
  - '@ugrc/*'
  - uuid@11.1.1
  - esbuild@0.28.1
  - form-data@4.0.6
  - form-data@2.5.6
  - '@opentelemetry/core@2.8.0'
  - undici@6.27.0
  - ts-deepmerge@8.0.0
  - morgan@1.10.2
  - websocket-driver@0.7.5
  - protobufjs@7.6.3
  - brace-expansion@2.1.2
  - brace-expansion@1.1.16
  - brace-expansion@5.0.7
  - js-yaml@4.3.0
  - tar@7.5.18
  - tar@7.5.19
  - tar@7.5.17
  - shell-quote@1.8.5
  - protobufjs@7.6.5
  - body-parser@2.3.0
  - body-parser@1.20.6
  - hono@4.12.25
  - hono@4.12.27
  - '@hono/node-server@2.0.5'
  - immutable@5.1.8
  - fast-uri@3.1.4
  - tar@7.5.21
  - re2@1.25.2
  - brace-expansion@1.1.17
  - brace-expansion@2.1.3
  - brace-expansion@5.0.8
  - undici@6.28.0
  - fast-uri@3.1.5
  - ip-address@10.3.1
  - ip-address@10.2.2
  - ip-address@10.2.1
  - hono@4.12.34
  - brace-expansion@5.0.9
  - brace-expansion@2.1.4
  - brace-expansion@1.1.18
  - js-yaml@4.3.1
  - re2@1.26.1
  - re2@1.25.1
  - fast-uri@3.1.3

overrides:
  diff@>=4.0.0 <4.0.4: '>=4.0.4'
  fast-xml-parser@>=4.3.6 <=5.3.3: '>=5.3.4'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  happy-dom@<20.0.0: '>=20.0.0'
  happy-dom@<20.0.2: '>=20.0.2'
  js-yaml@<3.14.2: '>=3.14.2'
  jws@<3.2.3: '>=3.2.3'
  jws@=4.0.0: '>=4.0.1'
  node-forge@<1.3.2: '>=1.3.2'
  qs@<6.14.1: '>=6.14.1'
  tar@<7.5.7: '>=7.5.7'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
  tmp@<=0.2.3: '>=0.2.4'
  vite@>=6.0.0 <=6.4.0: '>=6.4.1'
allowBuilds:
  '@firebase/util': true
  '@parcel/watcher': true
  '@vaadin/vaadin-usage-statistics': true
  core-js: true
  esbuild: true
  protobufjs: true
  re2: true
  unrs-resolver: true
