[tool.ruff]
ignore = ["E501"]
[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests", "src"]
norecursedirs = [".env", "data", "maps", ".github", ".vscode"]
console_output_style = "count"
addopts = "--ruff --cov-branch --cov=download --cov-report term --cov-report xml:cov.xml --instafail"
