import SimpleTable from './SimpleTable';

export default {
  title: 'Utah Design System/SimpleTable',
  component: SimpleTable,
};

const data = [
  {
    OBJECTID: 6606,
    FACILITYID: 2697,
    TANKID: 1,
    ALTTANKID: '1',
    FEDERALREG: 'Yes',
    ABOVETANK: 'No',
    REGAST: 'No',
    TANKEMERGE: 'No',
    TANKSTATUS: 'Permanently Out of Use',
    TANKCAPACI: 10000,
    SUBSTANCED: 'Gasoline',
    SUBSTANCET: 'Regular',
    TANKMATDES: 'Galvanic Cathodic Protection (STIP3)',
    TANKMODSDE: 'None',
    PIPEMATDES: 'Galvanized Steel',
    PIPEMODDES: 'None',
    DATEINSTAL: 547776000000,
    DATECLOSE: 1603065600000,
    CLOSURESTA: 'Tank removed from ground',
    INCOMPLIAN: 'No',
    PST_FUND: 'Yes',
    OTHERTYPE: null,
    FORKLIFT_HASH: 'e8d2155f816388e4',
  },
  {
    OBJECTID: 6607,
    FACILITYID: 2697,
    TANKID: 2,
    ALTTANKID: '2',
    FEDERALREG: 'Yes',
    ABOVETANK: 'No',
    REGAST: 'No',
    TANKEMERGE: 'No',
    TANKSTATUS: 'Permanently Out of Use',
    TANKCAPACI: 10000,
    SUBSTANCED: 'Gasoline',
    SUBSTANCET: 'Premium',
    TANKMATDES: 'Galvanic Cathodic Protection (STIP3)',
    TANKMODSDE: 'None',
    PIPEMATDES: 'Galvanized Steel',
    PIPEMODDES: 'None',
    DATEINSTAL: 547776000000,
    DATECLOSE: 1603065600000,
    CLOSURESTA: 'Tank removed from ground',
    INCOMPLIAN: 'No',
    PST_FUND: 'Yes',
    OTHERTYPE: null,
    FORKLIFT_HASH: 'd3ecae69ca471e77',
  },
  {
    OBJECTID: 6608,
    FACILITYID: 2697,
    TANKID: 3,
    ALTTANKID: '3',
    FEDERALREG: 'Yes',
    ABOVETANK: 'No',
    REGAST: 'No',
    TANKEMERGE: 'No',
    TANKSTATUS: 'Permanently Out of Use',
    TANKCAPACI: 5000,
    SUBSTANCED: 'Gasoline',
    SUBSTANCET: null,
    TANKMATDES: 'Asphalt Coated or Bare Steel',
    TANKMODSDE: 'None',
    PIPEMATDES: 'Unknown',
    PIPEMODDES: 'None',
    DATEINSTAL: -83376000000,
    DATECLOSE: 533779200000,
    CLOSURESTA: 'Tank Removed from Ground',
    INCOMPLIAN: 'No',
    PST_FUND: 'No',
    OTHERTYPE: null,
    FORKLIFT_HASH: 'd7450f31814c8c3c',
  },
  {
    OBJECTID: 6609,
    FACILITYID: 2697,
    TANKID: 4,
    ALTTANKID: '4',
    FEDERALREG: 'Yes',
    ABOVETANK: 'No',
    REGAST: 'No',
    TANKEMERGE: 'No',
    TANKSTATUS: 'Permanently Out of Use',
    TANKCAPACI: 5000,
    SUBSTANCED: 'Gasoline',
    SUBSTANCET: null,
    TANKMATDES: 'Asphalt Coated or Bare Steel',
    TANKMODSDE: 'None',
    PIPEMATDES: 'Unknown',
    PIPEMODDES: 'None',
    DATEINSTAL: -83376000000,
    DATECLOSE: 533779200000,
    CLOSURESTA: 'Tank Closed in Place',
    INCOMPLIAN: 'No',
    PST_FUND: 'No',
    OTHERTYPE: null,
    FORKLIFT_HASH: 'edebc35863bf6253',
  },
  {
    OBJECTID: 18641,
    FACILITYID: 2697,
    TANKID: 5,
    ALTTANKID: '1',
    FEDERALREG: 'Yes',
    ABOVETANK: 'No',
    REGAST: 'No',
    TANKEMERGE: 'No',
    TANKSTATUS: 'Currently In Use',
    TANKCAPACI: 12000,
    SUBSTANCED: 'Gasoline',
    SUBSTANCET: 'Regular',
    TANKMATDES: 'Fiberglass Reinforced Plastic',
    TANKMODSDE: 'Double-Walled',
    PIPEMATDES: 'Flexible Plastic',
    PIPEMODDES: 'Double-Walled',
    DATEINSTAL: 1603324800000,
    DATECLOSE: null,
    CLOSURESTA: null,
    INCOMPLIAN: 'Yes',
    PST_FUND: 'Yes',
    OTHERTYPE: null,
    FORKLIFT_HASH: 'f2f0a79fcbdc8864',
  },
  {
    OBJECTID: 18700,
    FACILITYID: 2697,
    TANKID: 6,
    ALTTANKID: '2A',
    FEDERALREG: 'Yes',
    ABOVETANK: 'No',
    REGAST: 'No',
    TANKEMERGE: 'No',
    TANKSTATUS: 'Currently In Use',
    TANKCAPACI: 7000,
    SUBSTANCED: 'Gasoline',
    SUBSTANCET: 'Premium',
    TANKMATDES: 'Fiberglass Reinforced Plastic',
    TANKMODSDE: 'Double-Walled',
    PIPEMATDES: 'Flexible Plastic',
    PIPEMODDES: 'Double-Walled',
    DATEINSTAL: 1603324800000,
    DATECLOSE: null,
    CLOSURESTA: null,
    INCOMPLIAN: 'Yes',
    PST_FUND: 'Yes',
    OTHERTYPE: null,
    FORKLIFT_HASH: 'dd8745cd31cd4f1f',
  },
  {
    OBJECTID: 19777,
    FACILITYID: 2697,
    TANKID: 7,
    ALTTANKID: '2B',
    FEDERALREG: 'Yes',
    ABOVETANK: 'No',
    REGAST: 'No',
    TANKEMERGE: 'No',
    TANKSTATUS: 'Currently In Use',
    TANKCAPACI: 5000,
    SUBSTANCED: 'Diesel',
    SUBSTANCET: null,
    TANKMATDES: 'Fiberglass Reinforced Plastic',
    TANKMODSDE: 'Double-Walled',
    PIPEMATDES: 'Flexible Plastic',
    PIPEMODDES: 'Double-Walled',
    DATEINSTAL: 1603324800000,
    DATECLOSE: null,
    CLOSURESTA: null,
    INCOMPLIAN: 'Yes',
    PST_FUND: 'Yes',
    OTHERTYPE: null,
    FORKLIFT_HASH: 'f3db4fb3ee52dbc2',
  },
];
const columns = [
  {
    accessorKey: 'FACILITYID',
  },
  {
    accessorKey: 'TANKID',
  },
  {
    accessorKey: 'ALTTANKID',
  },
  {
    accessorKey: 'FEDERALREG',
  },
  {
    accessorKey: 'ABOVETANK',
  },
  {
    accessorKey: 'REGAST',
  },
  {
    accessorKey: 'TANKEMERGE',
  },
  {
    accessorKey: 'TANKSTATUS',
  },
  {
    accessorKey: 'TANKCAPACI',
  },
  {
    accessorKey: 'SUBSTANCED',
  },
  {
    accessorKey: 'SUBSTANCET',
  },
  {
    accessorKey: 'TANKMATDES',
  },
  {
    accessorKey: 'TANKMODSDE',
  },
  {
    accessorKey: 'PIPEMATDES',
  },
  {
    accessorKey: 'PIPEMODDES',
  },
  {
    accessorKey: 'DATEINSTAL',
  },
  {
    accessorKey: 'DATECLOSE',
  },
  {
    accessorKey: 'CLOSURESTA',
  },
  {
    accessorKey: 'INCOMPLIAN',
  },
  {
    accessorKey: 'PST_FUND',
  },
  {
    accessorKey: 'OTHERTYPE',
  },
  {
    accessorKey: 'FORKLIFT_HASH',
  },
];

export const Default = () => (
  <div style={{ height: '210px', width: '665px' }}>
    <SimpleTable
      data={data}
      columns={columns}
      caption="test caption"
      className="h-full w-full overflow-auto"
    />
  </div>
);
