# five main fields
ID = 'ID'
NAME = 'NAME'
ADDRESS = 'ADDRESS'
CITY = 'CITY'
TYPE = 'TYPE'
ENVIROAPPLABEL = 'ENVIROAPPLABEL'
ENVIROAPPSYMBOL = 'ENVIROAPPSYMBOL'

sourceData = 'sourceData'
sgidName = 'sgidName'
name = 'name'
description = 'description'
metaDataUrl = 'metaDataUrl'
heading = 'heading'
geometryType = 'geometryType'
url = 'url'
index = 'index'
fields = 'fields'
docLink = 'docLink'
gramaLink = 'gramaLink'
additionalLink = 'additionalLink'
additionalLinkFields = 'additionalLinkFields'
secure = 'secure'
specialFilters = 'specialFilters'
specialFiltersDefaultOn = 'specialFiltersDefaultOn'
additionalSearches = 'additionalSearches'
sortField = 'sortField'

queryLayers = 'queryLayers'
relatedTables = 'relatedTables'
otherLinks = 'otherLinks'
