export const fieldNames = {
  queryLayers: {
    additionalInformation: 'Additional Information',
    addressField: 'ADDRESS',
    additionalSearches: 'Additional Searches',
    cityField: 'CITY',
    codedValues: 'Coded Values',
    comments: 'Comments',
    customSymbologyField: 'Custom Symbology Field',
    divisionHeading: 'Division Heading',
    documentSearch: 'Document Search',
    geometryType: 'Geometry Type',
    gramaRequest: 'GRAMA Request',
    identifyAttributes: 'Identify Attributes',
    idField: 'ID',
    layerDescription: 'Layer Description',
    legendTitle: 'Legend Title',
    mapLabelField: 'Map Label Field',
    metadataLink: 'Metadata Link',
    name: 'Name',
    nameField: 'NAME',
    oidField: 'OID Field',
    permitInformation: 'Permit Information',
    relatedTables: 'Related Tables',
    secure: 'Secure',
    sgidFeatureClassName: 'SGID Feature Class Name',
    sortField: 'Sort Field',
    specialFilterDefaultToOn: 'Special Filter Default To On',
    specialFilters: 'Special Filters',
    typeField: 'TYPE',
  },
  relatedTables: {
    tabName: 'Tab Name',
    sgidTableName: 'SGID Table Name',
    oidField: 'OID Field',
    fields: 'Fields',
    additionalInformation: 'Additional Information',
    additionalInformationLinkFields: 'Additional Information Link Fields',
  },
  links: {
    id: 'ID',
    description: 'Description',
    url: 'URL',
  },
};
