define([
    './download/SpecDownload',

    './map/SpecLegend',
    './map/SpecMapButton',
    './map/SpecMapController',
    './map/SpecMeasureTool',
    './map/SpecPrint',
    './map/SpecReferenceLayerToggle',
    './map/SpecScaleDependentReferenceLayerToggle',

    './search/SpecAdditionalSearch',
    './search/SpecAddress',
    './search/SpecCheckboxFilter',
    './search/SpecCity',
    './search/SpecCoordinates',
    './search/SpecCounty',
    './search/SpecDateFilter',
    './search/SpecFieldFilter',
    './search/SpecGridRowHeader',
    './search/SpecID',
    './search/SpecIdentifyPane',
    './search/SpecQueryLayer',
    './search/SpecQueryLayerFilter',
    './search/SpecQueryLayerHeader',
    './search/SpecRadioFilter',
    './search/SpecRelatedTableGrid',
    './search/SpecRelatedTables',
    './search/SpecResultLayer',
    './search/SpecResultsGrid',
    './search/SpecSearch',
    './search/SpecShape',
    './search/SpecSiteName',
    './search/SpecStream',

    './security/Spec_LayersMixin',
    './security/Spec_RequestPane',
    './security/Spec_UserAdminPendingUser',
    './security/Spec_UserAdminUser',

    './Spec_CollapsibleMixin',
    './Spec_formatDates',
    './Spec_PopoverMixin',
    './SpecApp',
    './SpecCheckbox',
    './Spec_config'
]);
