require([
    'tests/unit/download/SpecDownload',

    'tests/unit/map/SpecLegend',
    'tests/unit/map/SpecMapButton',
    'tests/unit/map/SpecMapController',
    'tests/unit/map/SpecMeasureTool',
    'tests/unit/map/SpecPrint',
    'tests/unit/map/SpecReferenceLayerToggle',
    'tests/unit/map/SpecScaleDependentReferenceLayerToggle',

    'tests/unit/search/SpecAdditionalSearch',
    'tests/unit/search/SpecAddress',
    'tests/unit/search/SpecCheckboxFilter',
    'tests/unit/search/SpecCity',
    'tests/unit/search/SpecCoordinates',
    'tests/unit/search/SpecCounty',
    'tests/unit/search/SpecDateFilter',
    'tests/unit/search/SpecFieldFilter',
    'tests/unit/search/SpecGridRowHeader',
    'tests/unit/search/SpecID',
    'tests/unit/search/SpecIdentifyPane',
    'tests/unit/search/SpecQueryLayer',
    'tests/unit/search/SpecQueryLayerFilter',
    'tests/unit/search/SpecQueryLayerHeader',
    'tests/unit/search/SpecRadioFilter',
    'tests/unit/search/SpecRelatedTableGrid',
    'tests/unit/search/SpecRelatedTables',
    'tests/unit/search/SpecResultLayer',
    'tests/unit/search/SpecResultsGrid',
    'tests/unit/search/SpecSearch',
    'tests/unit/search/SpecShape',
    'tests/unit/search/SpecSiteName',
    'tests/unit/search/SpecStream',

    'tests/unit/security/Spec_LayersMixin',
    'tests/unit/security/Spec_RequestPane',
    'tests/unit/security/Spec_UserAdminPendingUser',
    'tests/unit/security/Spec_UserAdminUser',

    'tests/unit/Spec_CollapsibleMixin',
    'tests/unit/Spec_formatDates',
    'tests/unit/Spec_PopoverMixin',
    'tests/unit/SpecApp',
    'tests/unit/SpecCheckbox',
    'tests/unit/Spec_config'
]);
