name: Pull Request Events
on: pull_request

permissions:
  contents: write
  id-token: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test-unit:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Set up code
        uses: actions/checkout@v4

      - name: ⎔ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: 📥 Download dependencies
        run: |
          npm ci
          cd functions
          npm ci
          cd ..

      - name: 🧪 Run tests
        run: npm run test

      - name: 🔍 Lint
        run: npm run lint

  deploy-preview:
    name: Firebase preview
    runs-on: ubuntu-latest
    needs: [test-unit]
    if: ${{ github.event.sender.type == 'User' }}
    environment:
      name: dev

    steps:
      - name: 🚀 Deploy
        uses: agrc/firebase-website-deploy-composite-action@v1
        with:
          prebuild-command: |
            cd functions
            npm ci
            cd ..
          build-command: export NODE_OPTIONS=--max_old_space_size=4096 && npm run build:stage
          preview: yes
          project-id: ${{ secrets.PROJECT_ID }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          identity-provider: ${{ secrets.IDENTITY_PROVIDER }}
          service-account-email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_DISCOVER_KEY: ${{ secrets.VITE_DISCOVER_KEY }}
          VITE_WEB_API_KEY: ${{ secrets.PREVIEW_WEB_API_KEY }}
