name: Pull Request Events
on: pull_request

permissions:
  contents: write
  id-token: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test-unit:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Set up code
        uses: actions/checkout@v4

      - name: ⎔ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: 📥 Download dependencies
        run: |
          npm ci
          cd functions
          npm ci
          cd ..

      - name: 🧪 Run tests
        run: npm run test

      - name: 🔍 Lint
        run: npm run lint

  deploy-preview:
    name: Firebase preview
    runs-on: ubuntu-latest
    needs: [test-unit]
    if: ${{ github.event.sender.type == 'User' }}
    environment:
      name: dev

    steps:
      - name: 🚀 Deploy Firebase
        uses: agrc/firebase-website-deploy-composite-action@v1
        with:
          identity-provider: ${{ secrets.IDENTITY_PROVIDER }}
          service-account-email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          project-id: ${{ secrets.PROJECT_ID }}
          prebuild-command: |
            cd functions
            npm ci
            cd ..
          build-command: npm run build:stage
        env:
          VITE_FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
          VITE_DISCOVER_KEY: ${{ secrets.DISCOVER_KEY }}
          VITE_WEB_API_KEY: ${{ secrets.WEB_API_KEY }}
          VITE_DOWNLOAD_URL: ${{ secrets.DOWNLOAD_URL }}
          NODE_OPTIONS: --max-old-space-size=7168
