name: Release Events

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run tests against"
        type: environment
        required: true

permissions:
  id-token: write
  deployments: write

env:
  MEMORY: 4G
  TIMEOUT: 30m

jobs:
  deploy-dev:
    name: Deploy to dev
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://enviro.dev.utah.gov
    if: github.event.release.prerelease == true

    steps:
      - name: ⬇️ Set up code
        uses: actions/checkout@v6.0.2

      - name: 🚀 Deploy Firebase
        uses: agrc/firebase-website-deploy-composite-action@v2
        with:
          identity-provider: ${{ secrets.IDENTITY_PROVIDER }}
          service-account-email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          project-id: ${{ secrets.PROJECT_ID }}
          prebuild-command: |
            cd functions
            pnpm install --frozen-lockfile
            cd ..
          build-command: pnpm run build:stage
        env:
          VITE_FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
          VITE_DISCOVER_KEY: ${{ secrets.DISCOVER_KEY }}
          VITE_WEB_API_KEY: ${{ secrets.WEB_API_KEY }}
          VITE_DOWNLOAD_URL: ${{ secrets.DOWNLOAD_URL }}
          NODE_OPTIONS: --max-old-space-size=7168

      - name: 🏃 Deploy Cloud Run
        uses: agrc/cloud-run-docker-deploy-composite-action@v2
        with:
          docker-context: ./cloudrun
          docker-file: ./cloudrun/Dockerfile
          identity-provider: ${{ secrets.IDENTITY_PROVIDER }}
          service-account-email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          project-id: ${{ secrets.PROJECT_ID }}
          service: download
          flags: |
            --service-account=cloud-run-sa@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
            --max-instances=10
            --min-instances=0
            --allow-unauthenticated
            --memory=${{ env.MEMORY }}
            --timeout=${{ env.TIMEOUT }}
            --concurrency=1
          env-vars: |
            BUCKET=${{ secrets.PROJECT_ID }}-downloads
            CLOUD_RUN_PROJECT=${{ secrets.PROJECT_ID }}
            CLOUD_RUN_LOCATION=us-central1
            CLOUD_RUN_JOB=download-worker

      - name: 🧰 Deploy Cloud Run Job
        uses: ./.github/actions/deploy-download-worker
        with:
          project-id: ${{ secrets.PROJECT_ID }}
          service-account: cloud-run-sa@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
          bucket: ${{ secrets.PROJECT_ID }}-downloads
          memory: ${{ env.MEMORY }}
          timeout: ${{ env.TIMEOUT }}

  deploy-prod:
    name: Deploy to production
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://enviro.deq.utah.gov
    if: github.event.release.prerelease == false

    steps:
      - name: ⬇️ Set up code
        uses: actions/checkout@v6.0.2

      - name: 🚀 Deploy Firebase
        uses: agrc/firebase-website-deploy-composite-action@v2
        with:
          identity-provider: ${{ secrets.IDENTITY_PROVIDER }}
          service-account-email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          project-id: ${{ secrets.PROJECT_ID }}
          service-now-instance: ${{ secrets.SN_INSTANCE }}
          service-now-table: ${{ secrets.SN_TABLE }}
          service-now-system-id: ${{ secrets.SN_SYS_ID }}
          service-now-username: ${{ secrets.SN_USERNAME }}
          service-now-password: ${{ secrets.SN_PASSWORD }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          prebuild-command: |
            cd functions
            pnpm install --frozen-lockfile
            cd ..
          build-command: pnpm run build:prod
        env:
          VITE_FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
          VITE_DISCOVER_KEY: ${{ secrets.DISCOVER_KEY }}
          VITE_WEB_API_KEY: ${{ secrets.WEB_API_KEY }}
          VITE_DOWNLOAD_URL: ${{ secrets.DOWNLOAD_URL }}

      - name: 🏃 Deploy Cloud Run
        uses: agrc/cloud-run-docker-deploy-composite-action@v2
        with:
          docker-context: ./cloudrun
          docker-file: ./cloudrun/Dockerfile
          identity-provider: ${{ secrets.IDENTITY_PROVIDER }}
          service-account-email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          project-id: ${{ secrets.PROJECT_ID }}
          service: download
          flags: |
            --service-account=cloud-run-sa@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
            --max-instances=30
            --min-instances=0
            --allow-unauthenticated
            --memory=${{ env.MEMORY }}
            --timeout=${{ env.TIMEOUT }}
            --concurrency=1
          env-vars: |
            BUCKET=${{ secrets.PROJECT_ID }}-downloads
            CLOUD_RUN_PROJECT=${{ secrets.PROJECT_ID }}
            CLOUD_RUN_LOCATION=us-central1
            CLOUD_RUN_JOB=download-worker

      - name: 🧰 Deploy Cloud Run Job
        uses: ./.github/actions/deploy-download-worker
        with:
          project-id: ${{ secrets.PROJECT_ID }}
          service-account: cloud-run-sa@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
          bucket: ${{ secrets.PROJECT_ID }}-downloads
          memory: ${{ env.MEMORY }}
          timeout: ${{ env.TIMEOUT }}

  notify:
    name: Notifications
    needs: deploy-prod
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Release Notifier
        uses: agrc/release-issue-notifications-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
